server:
  port: 8763
  servlet:
    context-path: /nessage
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: message
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
  #邮件配置
  mail:
    host: smtp.qq.com
    username: 2465588162@qq.com
    password: yiwjomtwslhfdjbj   #授权码
    default-encoding: utf-8
    protocol: smtp
    properties:
      mail:
        timeout: 1000
        ssl.trust: smtp.qq.com
        auth: true
# 是对纯文本通信协议的扩展。它提供一种方式将纯文本连接升级为加密连接（TLS或SSL），而不是另外使用一个端口作加密通信。
        starttls:
          enable: true
          required: true




#数据源
  datasource:
      name: test
      url: jdbc:mysql://localhost:3306/shop_member
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      druid:
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
